
module.exports = {
  // some nuxt config...
  plugins: [
    { src: '~plugins/nuxt-codemirror-plugin', ssr: false }
  ],
  // some nuxt config...
  css: [
    // ...
    'codemirror/lib/codemirror.css',
    'codemirror/theme/base16-dark.css',
    // more styles...
  ],
  // some nuxt config...
}
