export { default as example01 } from './01-video.vue'
export { default as example02 } from './02-video.vue'
export { default as example03 } from './03-video.vue'
export { default as example04 } from './04-video.vue'
export { default as example05 } from './05-video.vue'
